/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Retireaway Destination Profile
 */
export interface Destination {
  readonly averageLifeExpectancyAt65: number;
  readonly climate: string;
  readonly continent: string;
  readonly corruptionIndex: number;
  readonly costOfLivingIndex: number;
  readonly country: string;
  readonly crimeIndex: number;
  readonly description: string;
  readonly englishProficiencyScore: number;
  readonly expatCommunitySize: number;
  readonly expenses: {
    readonly single: {
      readonly amount: number;
      readonly currency: "USD";
    };
    readonly family: {
      readonly amount: number;
      readonly currency: "USD";
    };
  };
  readonly fragileStatesIndex: number;
  readonly groceriesIndex: number;
  readonly healthExpenditurePerCapita: {
    readonly amount: number;
    readonly currency: "USD";
  };
  readonly healthcareQualityIndex: number;
  readonly housing: {
    readonly rent: {
      readonly min: {
        readonly amount: number;
        readonly currency: "USD";
      };
      readonly max: {
        readonly amount: number;
        readonly currency: "USD";
      };
    };
    readonly buy: {
      readonly min: {
        readonly amount: number;
        readonly currency: "USD";
      };
      readonly max: {
        readonly amount: number;
        readonly currency: "USD";
      };
    };
  };
  readonly languages: {
    readonly name: string;
    readonly percentage: number;
  }[];
  readonly officialLanguage: string;
  readonly population: number;
  readonly religions: {
    readonly name: string;
    readonly percentage: number;
  }[];
  readonly restaurantIndex: number;
  readonly safetyIndex: number;
  readonly taxes: {
    readonly name: string;
    readonly rate: string;
  }[];
  readonly id: string;
  readonly image: string;
  readonly temperature: {
    readonly avg: number;
    readonly min: number;
    readonly max: number;
  };
  readonly visas: {
    readonly name: string;
    readonly duration: string;
    readonly description: string;
    readonly requirements: string[];
  }[];
}
